apiVersion: setera.com/v1
kind: NodeStore
metadata:
  name: nodestore-test-cluster-worker
  namespace: default
spec:
  name: "test-cluster-worker"
  selectors:
   node: "test-cluster-worker"
  tenants:
    tenant-green:
      name: "tenant-green"
      vni: 2
      tenant_cidr: "10.244.0.0/30"
      vtep_ip: "10.244.0.0"
      vtep_mac: "5e:7b:65:1e:f6:8c"
      bridge_ip: "10.244.0.1"
      bridge_mac: "a2:e9:a8:5b:d5:f7"
      pods:
        - name: "busybox-green-1"
          ip: "10.244.0.2"
          mac: "5e:29:5f:ea:ce:d9"
     
   