apiVersion: setera.com/v1
kind: NodeStore
metadata:
  name: nodestore-test-cluster-worker2
  namespace: default
spec:
  name: "test-cluster-worker2"
  selectors:
   node: "test-cluster-worker2"
  tenants:
    tenant-green:
      name: "tenant-green"
      vni: 2
      tenant_cidr: "10.244.1.0/30"
      vtep_ip: "10.244.1.0"
      vtep_mac: "de:8a:ee:a9:c4:25"
      bridge_ip: "10.244.1.1"
      bridge_mac: "d2:ba:5f:3b:77:ca"
      pods:
        - name: "busybox-green-2"
          ip: "10.244.1.2"
          mac: "5a:94:e0:8b:a1:27"
     