apiVersion: setera.com/v1
kind: Tenant
metadata:
  name: tenant-example
  namespace: default
spec:
  name: "TenantOne"
  vni: 1001
  nodes:
    - name: "node1"
      nodeIP: "192.168.1.10"
      prefix: 24
      vtepIp: "10.10.10.1"
      vtepMac: "00:1A:2B:3C:4D:5E"
    - name: "node2"
      nodeIP: "192.168.1.11"
      prefix: 24
      vtepIp: "10.10.10.2"
      vtepMac: "00:1A:2B:3C:4D:5F"
  zones:
    - name: "zone1"
      selectors:
        region: "us-east-1"
        availabilityZone: "us-east-1a"
    - name: "zone2"
      selectors:
        region: "us-west-1"
        availabilityZone: "us-west-1b"